### ISSUE TITLE
TypeError when trying to connect

### ISSUE THREAD

**Issue by Gabik21** [wix/corvid-external-db-mysql-adapter#15]
When trying to set up external database collection on wix the adapter throws this `TypeError`.
I have double-checked my config.json having the correct data and credentials. I also gave the mysql user all permissions, but it didn't change anything.

```
(node:15484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /home/mysql-adapter/corvid-external-db-mysql-adapter/client/database.js:40:27
    at Query.<anonymous> (/home/mysql-adapter/corvid-external-db-mysql-adapter/client/database.js:72:15)
    at Query.<anonymous> (/home/mysql-adapter/corvid-external-db-mysql-adapter/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/mysql-adapter/corvid-external-db-mysql-adapter/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/mysql-adapter/corvid-external-db-mysql-adapter/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /home/mysql-adapter/corvid-external-db-mysql-adapter/node_modules/mysql/lib/protocol/Protocol.js:404:18
    at Array.forEach (<anonymous>)
    at /home/mysql-adapter/corvid-external-db-mysql-adapter/node_modules/mysql/lib/protocol/Protocol.js:403:13
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
(node:15484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by evgolsh** [comment]
Did you try to set SQL_CONFIG env variable as described in README?
